# Generated by Django 5.2.7 on 2025-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='category_name', max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, db_column='category_image', null=True, upload_to='main/css/admin/pics/')),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=250)),
                ('user_email', models.CharField(db_column='user_email', max_length=100, unique=True)),
                ('user_password', models.CharField(db_column='user_password', max_length=25)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('item_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='product_name', max_length=250)),
                ('item_quantity', models.IntegerField(db_column='product_quantity')),
                ('item_description', models.CharField(db_column='product_description', max_length=500)),
                ('item_price', models.DecimalField(db_column='product_price', decimal_places=2, max_digits=10)),
                ('item_image', models.ImageField(db_column='product_image', upload_to='main/css/admin/pics/')),
            ],
            options={
                'db_table': 'products_furniture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(db_column='subcategory_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='subcategory_name', max_length=250, unique=True)),
            ],
            options={
                'db_table': 'subcategory',
                'managed': False,
            },
        ),
    ]
