# Generated by Django 5.2.7 on 2025-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('history_id', models.AutoField(db_column='history_id', primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_column='viewed_at')),
            ],
            options={
                'db_table': 'browsing_history',
                'ordering': ['-viewed_at'],
                'managed': False,
            },
        ),
    ]
