# Generated by Django 5.2.7 on 2025-11-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_browsinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField(db_column='cart_quantity')),
                ('order_price', models.DecimalField(db_column='cart_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'user_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField(db_column='order_quantity')),
                ('order_price', models.DecimalField(db_column='order_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'user_order',
                'managed': False,
            },
        ),
    ]
